version: '3.9'

services:
  threat-dashboard:
    build: .
    container_name: pipeline_intelligence-threat-dashboard
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
    restart: always
